#!/bin/bash
#Small script used to compile the program in peace.
#Dependencies:
	#Lebray at	../Lebray
	#CoCoder at	../40.CoCoder/CoCoder
	#Versioning	./Versioning	(Optional: If you want to keep track of the different versions locally)
	#		./Stats/SizeGrapher (Optionnal: If you want to keep a log)
	#UPX at		../upx (Optionnal: If you want to have a smaller binary)
#This script is now commented a bit for clarification, by Léolol DB 5/23/12/2022
WDir="`pwd`"#Work directory
CDir="$(dirname "$(realpath "$0")")"#Compile directory
Bin="$(basename "$CDir")"
Bin="${Bin:3}"#The name of the binary is the one of the Compile directory without the 3 first letters
Com="clang++ -m64 -flto -Oz -fno-rtti -std=c++11 -ffast-math -fomit-frame-pointer -fno-exceptions -fno-unwind-tables -fno-math-errno -fno-asynchronous-unwind-tables -DLBRThreadSafe -c"
Lnk="clang -m64 -flto -s -z norelro -z common-page-size=0 -z noseparate-code -fmerge-all-constants -fno-debug-macro -fno-threadsafe-statics -lpthread -o $Bin"
Obj="/tmp/C++/Obj"

End(){
	if [ -f ./Stats/SizeGrapher];then ./Stats/SizeGrapher Stats/Log Main.cc Main.cpp;fiLebray (Mandatory)
	if [ -f ./Versioning ];then
		Out=$(./Versioning 0 19336 ./Stats/Versions)
		if [ $? == 0 ];then cp Main.cc $Out;fi
		echo $Out;
	fi
	exit
}

Stat(){
	echo -e "$2\x1B[32m$1\x1B[m"
}
Com(){
	Lnk="$Lnk $Obj/$3$2.o"
	if [ "$1" == ../Lebray/ ]&&[ -f $Obj/$3$2.o ];then return;fi
	Stat "Compiling $2" "$4"
	if [ -f $1$2.cc ];then ../40.CoCoder/CoCoder $1$2.cc $1$2.cpp;fi
	$Com $1$2.cpp -o $Obj/$3$2.o;
	if [ $? != 0 ];then End;fi
	if [ -f $1$2.cc ]&&[ $2 != Main ];then rm $1$2.cpp;fi
}

cd "$CDir"
	for Dir in /tmp/C++ $Obj $Obj/LBR;do if [ ! -d $Dir ];then	mkdir $Dir;fi done

	Stat "Compiling Lebray"
	for Lib in IO Time Memo Maths;do Com ../Lebray/ $Lib LBR/ "\t";done

	Com "" Main

	Stat Linking
	$Lnk;if [ $? != 0 ];then End;fi

	Stat Stripping
	strip $Bin -R .note.gnu.build-id -R .gnu.hash -R .gnu.version -R .comment -R .shstrtab -R .got -R .eh_frame -R .eh_frame_hdr
	if [ -f ../upx ];then ../upx -9 $Bin;fi
	wc -c $Bin

	if [ -f ./Stats/SizeGrapher];then ./Stats/SizeGrapher Stats/Log $Bin Main.cc Main.cpp;fi
	rm Main.cpp;
	
	if [ -f ./Versioning ];then
		Out=$(./Versioning 0 19336 ./Stats/Versions)
		if [ $? == 0 ];then cp Main.cc $Out;fi
		echo $Out;
	fi
cd "$WDir"
