#!/bin/bash
if [ -f ~/.config/fontconfig/ ];then
	# cmp --quiet ./fonts.conf ~/.config/fontconfig/fonts.conf
	# if [ $? == 0 ];then
	# 	rm -r ~/.config/fontconfig/
	# else
	# 	echo "~/.config/fontconfig/fonts.conf was modified, remove it yourself if you want."
	# fi
fi
sudo apt-get -y remove pypy
if [ -f /usr/bin/SnakySnail3 ];then
	mv /usr/bin/SnakySnail3 /usr/bin/python3
else
	echo SnakySnail3 not found
fi
if [ -f /usr/bin/SnakySnail ];then
	mv /usr/bin/SnakySnail "`realpath /usr/bin/python3`"
fi
