#!/bin/bash
if [ ! -f ~/.config/fontconfig/ ];then
	# mkdir ~/.config/fontconfig/
	# cp ./fonts.conf ~/.config/fontconfig/
fi

if [ ! -f /usr/bin/SnakySnail3 ] && [ ! -f /usr/bin/SnakySnail ];then
	A="`realpath /usr/bin/python3`"
	if [ -f $A ];then
		#sudo apt-get -y install pypy
		mv /usr/bin/python3 /usr/bin/SnakySnail3
		ln -s /usr/bin/pypy /usr/bin/python3
		if [ -f $A ];then
			mv $A /usr/bin/SnakySnail;
		fi
	else
		echo "/usr/bin/python3 is a lie!"
		echo "Cannot configure PyPy."
	fi
else
	echo "The files /usr/bin/SnakySnail3 and /usr/bin/SnakySnail are already present."
	echo "Cannot configure PyPy."
fi
